Feat/bypass protection
wallet-guard/wallet-guard-extension pull request #19
Opened 2023-03-25 00:58 UTC by mindofmar

Goals for this PR:
- [ ] Don't run simulation when Metamask chain id is not ETH mainnet (Arbitrum example)
- [ ] Bypass protection as seen on Rosco's extension tests

2023-04-08 23:55 UTC, AugmentedMode submitted a review, later dismissed
i think i understand most of it, but looking through code didnt find any issues nice work bro

2023-04-08 23:55 UTC, AugmentedMode commented on src/components/simulation/BypassSimulation.tsx
> +//     <>
remove this

2023-04-09 15:17 UTC, 0xultimate requested changes

2023-04-09 15:17 UTC, imblue-dabadee commented on src/components/simulation/BypassSimulation.tsx
Delete?

2023-04-09 15:17 UTC, imblue-dabadee commented on src/background.ts
> +chrome.runtime.onMessage.addListener((message: BrowserMessage, sender, sendResponse) => {
`sender` and `sendResponse` aren't used

2023-04-09 15:17 UTC, imblue-dabadee commented on src/background.ts
> +  if (message.type === BrowserMessageType.ProceedAnyway && 'url' in message) {
Kinda gross this type check w/ `&&`. What about?
 ```typescript
 if (message.type === BrowserMessageType.ProceedAnyway) {
    const { url, permanent } = message as ProceedAnywayMessageType;
    // ...
}
 else if (message.type === BrowserMessageType.ApprovedTxn) {
    const msg = message as ApprovedTxnMessageType;
    approvedTxns.push(msg.data) 
  } else if (message.type === BrowserMessageType.RunSimulation) {
    const msg = message as RunSimulationMessageType;
    clearOldSimulations().then(() => fetchSimulationAndUpdate(msg.data));
  }
  ```
  Also, why are `ApprovedTxnMessageType and `RunSimulationMessageType` different types when they have the same structure.

2023-04-09 15:17 UTC, imblue-dabadee commented on src/lib/helpers/chrome/messageHandler.ts
> +export function findApprovedTransaction(approvedTxns: RequestArgs[], txn: RequestArgs) {
ok I want interfaces instead lmao

2023-04-09 15:17 UTC, 0xultimate commented on src/background.ts
> +  const isApproved = findApprovedTransaction(approvedTxns, message.data);
This will cause a bug i.e. if a debug transaction with the same message.data exists, it will not open up the WG popup and bypass successfully again.

2023-04-10 05:44 UTC, mindofmar commented on src/lib/helpers/chrome/messageHandler.ts
> +export function findApprovedTransaction(approvedTxns: RequestArgs[], txn: RequestArgs) {
https://github.com/wallet-guard/wallet-guard-extension/pull/30

Here's what it would look like with interfaces

2023-04-10 05:54 UTC, mindofmar commented on src/background.ts
> +  if (message.type === BrowserMessageType.ProceedAnyway && 'url' in message) {
I was able to fix this in #30 lmk what you think

2023-04-10 05:55 UTC, mindofmar commented on src/background.ts
> +  const isApproved = findApprovedTransaction(approvedTxns, message.data);
yeah, once the user has clicked Continue within our popup there's not much we can do to differentiate that txn from the one that's created afterwards.

2023-04-10 13:37 UTC, 0xultimate commented
the bypass bug seems fixed except for eth_sign @mindofmar

2023-04-12 22:18 UTC, mindofmar commented
> the bypass bug seems fixed except for eth_sign @mindofmar

`eth_sign` has been deprecated in MetaMask which is why it won't popup

2023-04-12 23:03 UTC, 0xultimate approved these changes, later dismissed

2023-04-13 21:08 UTC, AugmentedMode approved these changes
nice work bro

2023-04-14 04:31 UTC, merged