New Endpoints
wallet-guard/wallet-guard-extension pull request #20
Opened 2023-03-29 16:01 UTC by mindofmar

2023-03-29 16:25 UTC, AugmentedMode submitted a review, later dismissed

2023-03-29 16:25 UTC, AugmentedMode commented
new endpoints are dope

2023-05-29 23:09 UTC, 0xultimate requested changes
Check comment

2023-05-29 23:09 UTC, 0xultimate commented on src/lib/environment.ts
> +export const SERVER_URL_PROD = 'https://api.walletguard.app/extension/v0';
We should still differentiate PDS and the TAS urls since their versions are independent of one another.

2023-05-29 23:09 UTC, imblue-dabadee commented on src/tests/server.test.ts
Nice

2023-05-30 02:56 UTC, mindofmar commented on src/lib/environment.ts
> +export const SERVER_URL_PROD = 'https://api.walletguard.app/extension/v0';
Any recommendations on how we do this? I hate seeing `pds` and `tas` in the path. But can agree that they can/should be versioned separately. However these aren't mutually exclusive, since we could just clone the PDS between `v0` and `v1`

2023-06-07 05:02 UTC, merged