refactor models to extend request args and match the given type for a…
wallet-guard/wallet-guard-extension pull request #30
Opened 2023-04-10 05:43 UTC by mindofmar

… transaction

2023-04-10 06:35 UTC, mindofmar commented on src/background.ts
> +    const { url, permanent } = message as ProceedAnywayMessageType;
To be clear: This works either way whether `ProceedAnywayMessageType` is a `type` or an `interface`

2023-04-11 23:27 UTC, 0xultimate requested changes

2023-04-11 23:27 UTC, 0xultimate commented on src/background.ts
>  chrome.runtime.onMessage.addListener((message: BrowserMessage, sender, sendResponse) => {
`sender` and `sendResponse` are not used.

2023-04-11 23:27 UTC, 0xultimate commented on src/background.ts
>        const domainName = getDomainNameFromURL(url);
Lines 48-49 is a TODO comment. Are we keeping this?
```javascript
      // TODO: Need to set this up for new Server
      //incrementFalsePositiveCount(domainName);
```

2023-04-11 23:27 UTC, 0xultimate commented on src/content-scripts/contentScripts.tsx
>    log.info({ request }, 'Request');
Do we want to be logging here?

2023-04-11 23:27 UTC, 0xultimate commented on src/lib/simulation/server.ts
> +import { ErrorType, SimulationErrorResponse, SimulationResponse, Transaction, TransactionArgs } from '../../models/simulation/Transaction';
`Transaction` is not used in this file.

2023-04-12 22:02 UTC, mindofmar commented on src/background.ts
>        const domainName = getDomainNameFromURL(url);
let's keep it for now

2023-04-12 22:02 UTC, mindofmar commented on src/background.ts
>  chrome.runtime.onMessage.addListener((message: BrowserMessage, sender, sendResponse) => {
would rather keep these because I think the `Browser` api prefers them typed and for making this function very explicit

2023-04-12 22:03 UTC, mindofmar commented on src/content-scripts/contentScripts.tsx
>    log.info({ request }, 'Request');
would rather have it than not tbh

2023-04-12 22:14 UTC, 0xultimate approved these changes

2023-04-12 22:14 UTC, merged