Better request type safety
wallet-guard/wallet-guard-extension pull request #58
Opened 2023-05-12 06:43 UTC by mindofmar

- [x] Use href instead of hostname for TAS URLs. This lets us know where txns truly originate
- [x] Add type safety to certain requests which were being malformed

2023-05-29 23:15 UTC, 0xultimate requested changes
Left comments

2023-05-29 23:15 UTC, 0xultimate commented on src/tests/convertObject.test.ts
> +        else if (typeof inputObj[x] === 'object') {
Hm will this break if inputObj[s] === null since typeof(null) returns object?

2023-05-30 16:12 UTC, mindofmar commented on src/tests/convertObject.test.ts
> +        else if (typeof inputObj[x] === 'object') {
ah wow nice catch. Yeah I'd imagine it would map `null` to `{}`. I can add a check for that. But are there any cases where `null` gets passed in as a transaction param?

2023-05-30 16:21 UTC, mindofmar commented on src/tests/convertObject.test.ts
> +        else if (typeof inputObj[x] === 'object') {
added check for nulls before the check for `object`. great find

2023-06-07 05:02 UTC, merged