Feat/chatweb3
wallet-guard/wallet-guard-extension pull request #74
Opened 2023-06-18 01:36 UTC by AugmentedMode

2023-06-20 01:29 UTC, mindofmar requested changes
first half of review

2023-06-20 01:29 UTC, mindofmar commented on src/background.ts
> +    id: 'ask-chatgpt',
change to `ask-chatweb3`

2023-06-20 01:29 UTC, mindofmar commented on src/background.ts
> +    if (currentChatWeb3Popup && currentChatWeb3Popup !== -1) {
remove this if statement. it is unreachable code

2023-06-20 01:29 UTC, mindofmar commented on src/background.ts
> +// Remove Simulation Popup
incorrect comment

2023-06-20 01:29 UTC, mindofmar commented on src/manifest.json
> +  "permissions": ["storage", "tabs", "alarms", "management", "notifications", "contextMenus"],
todo: make sure the `contextMenus` permission is not a warn or disable permission

2023-06-20 01:29 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatWeb3Tab.tsx
> +    const theme = localStorage.getItem('theme');
localStorage does not exist for chrome

2023-06-20 01:29 UTC, mindofmar commented on src/lib/hooks/useChat.ts
> +      // const chatBody: ChatBody = {
remove

2023-06-20 01:29 UTC, mindofmar commented on src/models/chatweb3/chatweb3.ts
> +export interface LocalStorage {
remove this

2023-06-20 01:29 UTC, mindofmar commented on src/models/chatweb3/chatweb3.ts
> +export interface ChatBody {
this is unused

2023-06-20 01:29 UTC, mindofmar commented on webpack/webpack.common.js
> +      process: 'process/browser.js',
do we need both `browser` and `browser.js`?

2023-06-20 01:29 UTC, mindofmar commented on src/pages/popup.tsx
> +  const [storedSimulations, setStoredSimulations] = useState<StoredSimulation[]>([]);
remove this

2023-06-20 01:29 UTC, mindofmar commented on src/pages/popup.tsx
> +            showChatWeb3={showChatWeb3}
this is always going to be true because you have the ternary statement above

look into whether this is being passed into lower level components

2023-06-20 01:29 UTC, mindofmar commented on src/pages/popup.tsx
> +        <div style={{ height: '100vh' }}>
remove this div - change it back to `<>`

2023-06-20 01:29 UTC, mindofmar commented on src/lib/environment.ts
> +export const CHATWEB3_SERVER_URL_PROD = 'http://chatweb3-alb-prod-980216059.us-east-2.elb.amazonaws.com';
todo- remove this and use SERVER_URL_PROD

2023-06-20 01:29 UTC, mindofmar commented on src/components/simulation/simulation.module.css
> +  .center-button {
unused css - remove this

2023-06-20 01:29 UTC, mindofmar commented on src/fonts/Inter-Bold.ttf
Todo - 

Create 2 production builds, one with and one without these fonts. If it's more than 1 MB difference, remove them

2023-06-20 03:33 UTC, mindofmar requested changes

2023-06-20 03:33 UTC, mindofmar commented on src/lib/helpers/chatweb3/questions.ts
> +export const chatWeb3Questions: ChatWeb3Questions = {
why do we have an original and refactored version of these?

2023-06-20 03:33 UTC, mindofmar commented on src/lib/helpers/chatweb3/questions.ts
> +export const chatWeb3QuestionsRefactored: ChatWeb3QuestionsRefactored = {
I'd like to have the whole team review these

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/PluginGrid.tsx
> +    console.log(`Selected plugin: ${pluginTitle}`);
should this function do anything?

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/PluginGrid.tsx
> +              key={index}
using `index` as a key is bad practice in React. I know it doesn't make a huge difference here, but adding this comment for future reference. With long lists, imagine you remove one of the array items early on in the list. Now nearly every single item (and therefore component) in that list has to re-render. The whole purpose of using `key` is for React to know that it doesn't have to re-render that component. `plugin.persona` would be a better key here

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/PluginGrid.tsx
> +// src/PluginGrid.tsx
remove this

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatWeb3Navbar.tsx
> +  const handleDropdownSelect = (model: any) => {
Is this in here in case we add support for more models in the future?

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/Chat.tsx
> +  showChatWeb3?: any;
shouldn't this be bool??

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/Chat.tsx
> +  storedSimulation?: any;
this also has a type. Please remove all `any`s here

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatWeb3Navbar.tsx
> +  showChatWeb3?: any;
These are not `any` - they have a type from the parent so let's pass those types down

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatWeb3Tab.tsx
> +  showChatWeb3?: any;
no `any`

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/PluginCard.tsx
> +// src/PluginCard.tsx
remove this

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/PluginCard.tsx
> +  onSend: (plugin: any) => void;
`plugin` should have a type

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatLoader.tsx
> +interface Props {}
remove this interface - no need for it if this component doesn't take props

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatLoader.tsx
> +import { IconCheck, IconCopy, IconEdit, IconRobot, IconUser, IconDots } from '@tabler/icons-react';
I don't see this being used - reminder to remove all unused imports please

2023-06-20 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatMessage.tsx
> +  lightMode: 'light' | 'dark';
this isn't used anywhere - can we remove it?

2023-06-20 16:42 UTC, mindofmar requested changes

2023-06-20 16:42 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/Chat.tsx
> +                    // setCurrentMessage({ role: 'user', content: 'plugin' });
remove commented code and add type to remove `any` on line above this

2023-06-20 16:42 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatInput.tsx
> +        console.log(getDomainNameFromURL(tabs[0].url));
remove this console log.

2023-06-20 16:42 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatInput.tsx
> +    // TODO: need to only get url once, this url is fetched everytime a chunk is passed to the frontend
can you explain this?

2023-06-20 16:42 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatInput.tsx
> +                          ? "What's 'value' field?"
not sure this is the best question here - are these the questions we use from the txn screen?

2023-06-20 16:42 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/SystemPrompt.tsx
> +    if (conversation.prompt) {
useless if else statement here - you `setValue('')` in both cases

2023-06-20 16:42 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Markdown/CodeBlock.tsx
> +    navigator.clipboard.writeText(value).then(() => {
can you verify that this works? I think `clipboard` is one of chrome's extension permissions, so without it explicitly set does this api still work?

2023-06-20 16:42 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Markdown/CodeBlock.tsx
> +CodeBlock.displayName = 'CodeBlock';
what does this do?

2023-06-20 16:42 UTC, mindofmar commented on src/components/simulation/ConfirmSimulationButton.tsx
> +  showChatWeb3?: any;
no `any`

2023-06-20 16:42 UTC, mindofmar commented on src/components/simulation/ConfirmSimulationButton.tsx
> +              posthog.capture('chatweb3 from tas clicked');
I think we want a more generic event here.

How about `posthog.capture('chatweb3 opened', { source: 'simulation' })`. This way we can set the source to other things like 'hotkey' or 'dashboard' and add breakdowns to the most popular locations users are using it from

2023-06-20 16:42 UTC, mindofmar commented on src/lib/helpers/chatweb3/conversation.ts
> +export const updateConversation = (updatedConversation: Conversation, allConversations: Conversation[]) => {
this entire function is very confusing and doesn't tell me much, if anything, of what this is does. add a comment plz.

2023-06-20 16:42 UTC, mindofmar commented on src/lib/helpers/chatweb3/conversation.ts
> +    all: updatedConversations,
a large part of why this is confusing is because you have 3 variables with very similar names here.

`updatedConversation`, `updatedConversations` and `allConversations`

2023-06-20 16:42 UTC, mindofmar commented on src/lib/hooks/useChat.ts
> +        res = await fetch(CHATWEB3_SERVER_URL_PROD + '/v2/chat', {
use API GW URL

2023-06-20 16:42 UTC, mindofmar commented on src/lib/hooks/useChat.ts
> +        console.log('storedSimulation', storedSimulation);
you have a lot of these exact console logs to check the storedSimulation. Can we remove some of these?

2023-06-20 16:42 UTC, mindofmar commented on src/lib/hooks/useChat.ts
> +        res = await fetch(CHATWEB3_SERVER_URL_PROD + '/v2/simulation', {
don't forget to change this to `/chat/simulation` when you update to API GW

2023-06-20 16:42 UTC, mindofmar commented on src/lib/hooks/useChat.ts
> +      const response = new Response(res.body);
why are you wrapping this? pretty sure the `fetch` api already is type `Response`

2023-06-20 16:42 UTC, mindofmar commented on src/lib/hooks/useChat.ts
> +      } else {
remove this if else statement and replace with 2 ternary statements to set the `requestURL` and `requestBody`

2023-06-20 16:42 UTC, mindofmar commented on src/lib/hooks/useChat.ts
> +        if (isFirst) {
oh I understand what `isFirst` is now - maybe `isFirstMessage` would be a better name here

2023-06-20 16:42 UTC, mindofmar commented on src/lib/hooks/useChat.ts
> +      const reader = data.getReader();
try pulling this out into it's own function called like `processStream` or `processResponse` if you can

2023-06-20 16:55 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/Chat.tsx
> +              console.log('storedSimulation', storedSimulation);
again, can we remove this.

2023-06-20 16:57 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatInput.tsx
> +  const handleSend = (exampleQuestion?: string) => {
you need posthog here too - you only have posthog in the simulation popup rn

2023-06-20 17:29 UTC, AugmentedMode commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatInput.tsx
> +    // TODO: need to only get url once, this url is fetched everytime a chunk is passed to the frontend
i fixed this with the useEffect, removing old TODO comment

2023-06-20 17:29 UTC, AugmentedMode commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatInput.tsx
> +                          ? "What's 'value' field?"
Good idea will come up with better questions for the txn screen

2023-06-20 17:44 UTC, AugmentedMode commented on src/components/app-dashboard/tabs/chatweb3/components/Markdown/CodeBlock.tsx
> +    navigator.clipboard.writeText(value).then(() => {
this functionality seems to work! Will put this in the checklist of things to test in QA as well

2023-06-20 20:56 UTC, AugmentedMode commented on src/lib/hooks/useChat.ts
> +      const reader = data.getReader();
gonna leave it like this for now, i think a whole refactor of this file would be better, i solved it better on chatweb3 the website so will do a refactor in time to pull over updated code to replace this

2023-06-20 21:03 UTC, AugmentedMode commented on webpack/webpack.common.js
> +      process: 'process/browser.js',
i get this error when i dont have browser.js

**e/Desktop/wallet-guard/repos/wallet-guard-extension/node_modules/uvu/node_modules/kleur'**

**Did you mean 'browser.js'?**

**BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified**

**(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').**

**The extension in the request is mandatory for it to be fully specified.**

**Add the extension to the request.**

resolve 'process/browser' in '/Users/augmentedmode/Desktop/wallet-guard/repos/wallet-guard-extension/node_modules/uvu/node_modules/kleur'

Parsed request is a module

using description file: /Users/augmentedmode/Desktop/wallet-guard/repos/wallet-guard-extension/node_modules/uvu/node_modules/kleur/package.json (relative path: .)

Field 'browser' doesn't contain a valid alias configuration

resolve as module

**/Users/augmentedmode/**

2023-06-20 21:15 UTC, AugmentedMode commented on src/pages/popup.tsx
> +            showChatWeb3={showChatWeb3}
im using showChatWeb3 in lower level components. i did however remove fromSimulation since i can use the showChatWeb3 instead as well

2023-06-22 18:45 UTC, mindofmar commented on src/components/simulation/ConfirmSimulationButton.tsx
> +  setShowChatWeb3?: any;
another any

2023-06-22 19:31 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatWeb3Tab.tsx
> +  setShowChatWeb3?: any;
no any

2023-07-08 03:33 UTC, mindofmar requested changes

2023-07-08 03:33 UTC, mindofmar commented on public/images/chatweb3/wave.png
we already have a wave img somewhere in this folder

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/WelcomeModal.tsx
> +        <Button colorScheme='blue' mr={3} onClick={onClose}>
remove commented code

2023-07-08 03:33 UTC, mindofmar commented on src/pages/popup.tsx
> +          {/* // TODO: Need to remove chatweb3 button when there is no simulation */}
what is this todo?

2023-07-08 03:33 UTC, mindofmar commented on src/pages/popup.tsx
> +      posthog.onFeatureFlags(() => {
this is going to cause a ton of posthog events being in the popup. I don't think this should exist here

2023-07-08 03:33 UTC, mindofmar commented on src/components/simulation/SimulationHeader.tsx
> +                {/* <b className={`${styles['font-archivo-medium']} pr-2`}>Share</b> */}
remove commented code

2023-07-08 03:33 UTC, mindofmar commented on src/components/simulation/SimulationHeader.tsx
> +              posthog.capture('chatweb3 opened', { source: 'simulation' });
I don't think this event should be captured here. It should be captured from the chatweb3 component, and if there's a current simulation then we know it's from the simulation screen, otherwise it's hotkey. I want stats on hotkey usage

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/dashboard/DashboardTab.tsx
> +      {/* <WelcomeModal isOpen={chatweb3Welcome} onClose={toggleChatWeb3WelcomeModal} />
remove commented code

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/dashboard/DashboardTab.tsx
> +  const [chatweb3Welcome, setChatWeb3Welcome] = useState<boolean>(true);
what is this variable used for here?? I don't see any. refs

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/WelcomeModal.tsx
> +                  <img src="/images/chatweb3/wave.png" alt="" style={{ maxWidth: '70px' }} width={60} height={60} />
update ref here to my wave img

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/WelcomeModal.tsx
> +  onClose: any;
no any

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Markdown/CodeBlock.tsx
> +    if (!navigator.clipboard || !navigator.clipboard.writeText) {
can we use useClipboard here instead like the TAS popup just to be safe?

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Markdown/CodeBlock.tsx
> +  const downloadAsFile = () => {
please remove this functionality

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatWeb3Tab.tsx
> +  setShowChatWeb3?: any;
bump

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatWeb3Tab.tsx
> +  return (
wondering if this is where that posthog insight should be located?

2023-07-08 03:33 UTC, mindofmar commented on src/manifest.json
> +    "run-foo": {
why do you do this

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatLoader.tsx
> +        overflowWrap: 'anywhere',
could this be correlated to your overflow issue in the TAS popup?

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/ChatWeb3Navbar.tsx
> +  setShowChatWeb3?: any;
no any

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/Chat.tsx
> +  lightMode: 'light' | 'dark';
remove this

2023-07-08 03:33 UTC, mindofmar commented on src/components/app-dashboard/tabs/chatweb3/components/Chat/Chat.tsx
> +        backgroundColor: lightMode === 'dark' ? '#161616' : 'initial',
hardcode this to the dark output

2023-07-08 03:33 UTC, mindofmar commented on public/popup.html
> +<body style="background-color: #0e0e0e; height: 100vh; position: initial ">
TODO for me - create a branch to try and remove this while fixing the other padding related issues

2023-07-08 04:57 UTC, mindofmar commented on src/components/simulation/SimulationHeader.tsx
> +  setShowChatWeb3?: any;
remove any

2023-07-08 04:58 UTC, mindofmar approved these changes

2023-07-08 04:59 UTC, merged